### ISSUE TITLE
Booking Screen Style

### ISSUE THREAD

**Issue by Ch4s3d** [BC-MAY-21-RN/kata-05-reservacion-de-vuelos-k5-cb-reactive12#4]
# REQUIREMENTS
Create base style for Booking Screen

# DESIGN
![booking.png](https://images.zenhubusercontent.com/630fd69fb90c326ee43636c9/2a369213-cba4-4637-9e82-71d7fbaf1b2e)

**Comment by aguirre-valeria** [comment]
All is ok
